# Code by AkinoAlice@TyrantRey

version: "3.9"
services:
  Frontend:
    container_name: econ_ta_frontend
    restart: unless-stopped
    image: econ_afs_backend
    ports:
      - 5000:5000
    env_file: ".env"
