# Code by AkinoAlice@TyrantRey

version: "3.9"
services:
  mysql:
    container_name: backend_mysql
    restart: unless-stopped
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example_password

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.0
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
      - DEPLOY_MODE=STANDALONE
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  Backend:
    container_name: econ_ta_backend
    restart: unless-stopped
    image: econ_afs_backend:20250809-222733

    # overwrite the environmental variable
    environment:
      - MYSQL_HOST=mysql
      - MILVUS_HOST=milvus

    ports:
      - 8000:8000
    env_file: ".env"
    depends_on:
      mysql:
        condition: service_started
      milvus:
        condition: service_healthy