version: "3"
services:
  backend:
    image: llm_backend:1723358842
    container_name: backend
    environment:
      # Global variables
      - DEBUG=True

      # CORS Setting
      # - CORS_ALLOWED_ORIGIN="*"

      # JWT Settings
      - JWT_SECRET="secret_token"
      - JWT_ALGORITHM="HS256"

      # Admin Settings
      - ROOT_USERNAME="admin"
      - ROOT_PASSWORD="ADMIN-"

      # Mysql Setup
      - MYSQL_DEBUG=False
      - MYSQL_HOST=192.168.1.105
      - MYSQL_PORT=3307
      - MYSQL_USER_NAME=root
      - MYSQL_PASSWORD=example_password
      - MYSQL_DATABASE=FCU_LLM

      # Milvus Setup
      - MILVUS_DEBUG=False
      - MILVUS_HOST=192.168.1.105
      - MILVUS_PORT=19530
      - MILVUS_DEFAULT_COLLECTION_NAME=default
      - MILVUS_VECTOR_DIM=4096

      # # LLM Setup
      # REPO_ID=shenzhi-wang/Llama3-8B-Chinese-Chat-GGUF-4bit
      # LLM_MODEL=Llama3-8B-Chinese-Chat-q4_0-v2_1.gguf
      # HF_EMBEDDING_MODEL=shibing624/text2vec-base-chinese
      # volumes:
      #   - /path/of/model/:/FCU_LLM/model

      # API
      - API_URL=https://api-ams.twcc.ai/api
      - API_KEY=4bfbaa37-0262-4f5c-878f-8e9d509bad56

    ports:
      - 8081:8080
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_started
  mysql:
    image: mysql:latest
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    restart: unless-stopped
    ports:
     - 3307:3306